# Generated by Django 5.2.8 on 2026-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_week_unlocked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
