# Generated by Django 5.2.8 on 2026-05-13 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_interview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview_questions',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.courseweek'),
            preserve_default=False,
        ),
    ]
