# Generated by Django 6.0.5 on 2026-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_interview_questions_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_questions',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview_questions',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview_questions',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
