# Generated by Django 6.0.5 on 2026-06-05 06:46

from django.db import migrations

def populate_interview_stats(apps, schema_editor):
    Interview_questions = apps.get_model('curriculum', 'Interview_questions')
    Enrollment = apps.get_model('curriculum', 'Enrollment')
    
    for session in Interview_questions.objects.all():
        is_finished = False
        score = 0
        
        # Check system_metadata
        metadata = next((msg for msg in session.data if isinstance(msg, dict) and msg.get('role') == 'system_metadata'), None)
        if metadata:
            is_finished = metadata.get('finished', False)
            score = metadata.get('score', 0)
        else:
            # Fallback check
            is_finished = any(
                isinstance(msg, dict) and msg.get('role') == 'assistant' and 
                any(keyword in (msg.get('content') or '').lower() for keyword in ["assessment complete", "interview is complete", "score:"])
                for msg in session.data
            )
            if is_finished:
                try:
                    enrollment = Enrollment.objects.get(user=session.user)
                    if session.week.week_number < enrollment.current_week_unlocked:
                        score = 100
                    else:
                        score = 0
                except Exception:
                    score = 0
        
        if is_finished:
            session.is_finished = True
            session.score = score
            session.completed_at = session.created_at
            session.save()

def rollback_interview_stats(apps, schema_editor):
    Interview_questions = apps.get_model('curriculum', 'Interview_questions')
    for session in Interview_questions.objects.all():
        session.is_finished = False
        session.score = None
        session.completed_at = None
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_interview_questions_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_interview_stats, rollback_interview_stats),
    ]

